import React from 'react'
import type { Metadata } from 'next'
import MainLayout from '@/layout/Main/MainLayout'
import { AppProps } from 'next/app'
import '@/styles/globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function App({Component, pageProps}: AppProps ) {
  return (
    <>
      <MainLayout>
        <Component {...pageProps} />
      </MainLayout>
    </>
  )
}
export default App