import React from 'react'
import type { Metadata } from 'next'
import { AppProps } from 'next/app'
import Layout from '@/components/layout/Layout'
import '@/styles/globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function App({Component, pageProps}: AppProps ) {
  return (
    <>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}
export default App